name: developer-bootcamp-fy24

services:
  db:
    image: public.ecr.aws/docker/library/postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
    volumes:
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 3

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/var/workspaces"
    command: /bin/bash
    tty: true
    environment:
      TZ: Asia/Tokyo
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: sample_development
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: sample_development
    volumes:
      - ../:/var/workspaces
    depends_on:
      db:
        condition: service_healthy
